### PR TITLE
Added restartableTicks EventStream: a ticks EventStream whose interna…

### PR DESCRIPTION
**Pull request by JordanMartinez**
…l timer restarts whenever impulse emits an event.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
I tried writing the following test, and it failed with "Expected 2 but got 1." I'm not sure why:
````java
@Test
public void fxRestartableTicksTest() throws InterruptedException, ExecutionException {
    CompletableFuture<Integer> nTicks = new CompletableFuture<>();
    Platform.runLater(() -> {
        EventCounter counter = new EventCounter();
        EventSource<?> impulse = new EventSource<Void>();
        Subscription sub = EventStreams.restartableTicks(Duration.ofMillis(100), impulse)
                .subscribe(counter::accept);
        FxTimer.runLater(Duration.ofMillis(370), sub::unsubscribe);
        FxTimer.runLater(Duration.ofMillis(80),() -> impulse.push(null));
        FxTimer.runLater(Duration.ofMillis(260),() -> impulse.push(null));
        // 000: Start -> 80 (restart)
        // 080: Start
        // 180: End (tick)
        // 180: Start -> 80 (restart)
        // 260: Start
        // 360: End (tick)
        // 370: interrupted: 2 ticks
        // wait a little more to test that no more ticks arrive anyway
        FxTimer.runLater(Duration.ofMillis(550), () -> nTicks.complete(counter.get()));
    });
    assertEquals(2, nTicks.get().intValue());
}
````

**Comment by JordanMartinez** [comment]
Same for the other one: Expected 5 but got 4:
````java
@Test
public void fxRestartableTicks0Test() throws InterruptedException, ExecutionException {
    CompletableFuture<Integer> nTicks = new CompletableFuture<>();
    Platform.runLater(() -> {
        EventCounter counter = new EventCounter();
        EventSource<?> impulse = new EventSource<Void>();
        Subscription sub = EventStreams.restartableTicks0(Duration.ofMillis(100), impulse)
                .subscribe(counter::accept);
        FxTimer.runLater(Duration.ofMillis(370), sub::unsubscribe);
        FxTimer.runLater(Duration.ofMillis(80), () -> impulse.push(null));
        FxTimer.runLater(Duration.ofMillis(260), () -> impulse.push(null));
        // 000: 0 (tick) -> 80 (restart)
        // 080: 0 (tick)
        // 180: 0 (tick) -> 80 (restart)
        // 260: 0 (tick)
        // 360: 0 (tick)
        // 370: interrupted: 5 ticks
        // wait a little more to test that no more ticks arrive anyway
        FxTimer.runLater(Duration.ofMillis(550), () -> nTicks.complete(counter.get()));
    });
    assertEquals(5, nTicks.get().intValue());
}
````

**Comment by TomasMikula** [comment]
You only have 10ms allowed between the last tick (360) and unsubscribing (370). The granularity of a timer based on JavaFX animation is about 60fps, i.e. ~16.6ms.

**Comment by TomasMikula** [comment]
That means the tick and the unsubscription could have been scheduled in the same animation frame, and if unsubscription happens first, you don't get the tick.

**Comment by JordanMartinez** [comment]
That makes sense. By increasing it by 30ms, it passed.

**Pull request merged**
