### PR TITLE
EventStreams#ticks emits its value at time 0 (timer start) or at its given interval (timer end).

### PR DESCRIPTION
**Pull request by JordanMartinez**
The only think to check would be FxTimer's factory methods' javadoc. I'm guessing you will think of a simpler way of explaining it.

Note: I didn't implement `ticks0` for non-"JavaFX Application" Threads.

### CODE REVIEW

**Comment by TomasMikula** [comment]
I don't see any use for `create0` and `runLater0`. Whoever wants to do that can just execute the `action` right away.

**Comment by TomasMikula** [comment]
My IDE setting is to use wildcard imports only for static imports and nothing else. It would be great if you could use the same settings for this project to avoid noise in the commits.

**Comment by JordanMartinez** [comment]
> I don't see any use for create0 and runLater0. Whoever wants to do that can just execute the action right away.

Should I remove those completely then?

> My IDE setting is to use wildcard imports only for static imports and nothing else. It would be great if you could use the same settings for this project to avoid noise in the commits.

Ok. My IDE will optimize imports before it commits, so I'll go back and update the imports accordingly.
Still, why do you do that? Is there some advantage to it?

**Comment by TomasMikula** [comment]
I'm sure you can configure your IDE to not use `*` imports. Arguments can be made both for and against this convention. For me it is about being able to tell where a name comes from by just looking at the source code outside of any IDE (e.g. on GitHub). Another argument usually made is increasing the chance of name clashes.

**Comment by JordanMartinez** [comment]
> Another argument usually made is increasing the chance of name clashes.

Makes sense. Thanks for explaining that. I've only dealt with that issue once: javafx.scene.Node clashed with groovy.xml.Node (or whatever path it was). However, Groovy allows import aliasing, so that wasn't really an issue for me.

**Comment by JordanMartinez** [comment]
How's that?

**Comment by TomasMikula** [comment]
There's still some import shuffling noise, but the code looks good.

Some tests would be nice.

**Comment by JordanMartinez** [comment]
I'll create a new PR without the import noise tomorrow.

I haven't ever written a test before. However, looking at `TicksTest.java`, it seems like deriving one off of the `fxTest()` won't be that hard.

**Comment by JordanMartinez** [comment]
See the next pull request.

**Pull request closed without merging**
